### ISSUE TITLE
Remove the `tool.` part of the pyproject.toml section

### ISSUE THREAD

**Issue by lyz-code** [dbatten5/maison#42]
Hey @dbatten5, first of all, thanks for the package, it's awesome :)

Would it be possible that instead of using `[tool.acme]` we could use directly `[acme]`?

Thanks!

**Comment by dbatten5** [comment]
hey @lyz-code, thanks for raising an issue. just wondering why you prefer `[acme]` instead of `[tool.acme]`? i ask as having `[tool.x]` seems to be the standard practice, looking at big name tools like [isort](https://pycqa.github.io/isort/docs/configuration/config_files.html#pyprojecttoml-preferred-format), [black](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format) and [pytest](https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml) (although admittedly they use `[tool.pytest.ini_options]`

**Comment by lyz-code** [comment]
Ouch, ignore the issue, I don't know why I had in my mind that `black`, `pytest` and `isort` didn't use the `tool.` prefix.

**Comment by wwuck** [comment]
https://www.python.org/dev/peps/pep-0518/#tool-table


@lyz-code PEP 518 defines the tool table in `pyproject.toml`
